logging:
  level:
    com:
      mycompany:
        myapp: INFO
spring:
  application:
    name: AISampleApp
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/AISampleApp
    username: AISampleApp
  flyway:
    enabled: true
    locations: classpath:db/migration
application:
  logging:
    logstash:
      tcp:
        enabled: false
        host: localhost
        port: 5000
        ring-buffer-size: 8192
        shutdown_grace_period: PT1M
